apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g6rl0xu2m-go 
  janus-idp.io/tekton: g6rl0xu2m-go
  backstage.io/kubernetes-id: g6rl0xu2m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g6rl0xu2m-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml