apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: g6rl0xu2m-go-gitops
  description: This is GitOps manifest for g6rl0xu2m-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=g6rl0xu2m-go
    backstage.io/kubernetes-id: g6rl0xu2m-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: g6rl0xu2m-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:g6rl0xu2m-go
